name: Build RPCS3

defaults:
  run:
    shell: bash
on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}-${{ github.event_name }}
  cancel-in-progress: true

env:
  BUILD_REPOSITORY_NAME: ${{ github.repository }}
  BUILD_SOURCEBRANCHNAME: ${{ github.ref_name }}
  BUILD_PR_NUMBER: ${{ github.event.pull_request.number }}
  BUILD_SOURCEVERSION: ${{ github.sha }}
  BUILD_ARTIFACTSTAGINGDIRECTORY: ${{ github.workspace }}/artifacts/

jobs:
  Linux_Build:
    name: RPCS3 Linux x86 clang
    runs-on: ubuntu-24.04
    env:
      CCACHE_DIR: ${{ github.workspace }}/ccache
      DEPLOY_APPIMAGE: true
      APPDIR: "/rpcs3/build/appdir"
      ARTDIR: "/root/artifacts"
      RELEASE_MESSAGE: "/rpcs3/GitHubReleaseMessage.txt"
      COMPILER: clang
      RUN_UNIT_TESTS: github.event_name == 'pull_request' && 'ON' || 'OFF'
    steps:
      - name: Checkout repository
        uses: actions/checkout@main
        with:
          fetch-depth: 0

      - name: Restore build Ccache
        uses: actions/cache/restore@main
        id: restore-build-ccache
        with:
          path: ${{ env.CCACHE_DIR }}
          key: ${{ runner.os }}-ccache-clang-X64-${{ github.run_id }}
          restore-keys: ${{ runner.os }}-ccache-clang-X64-

      - name: Docker setup and build
        run: |
          docker pull --quiet rpcs3/rpcs3-ci-jammy:1.9
          docker run \
            -v $PWD:/rpcs3 \
            --env-file .ci/docker.env \
            -v ${{ env.CCACHE_DIR }}:/root/.ccache \
            -v ${{ env.BUILD_ARTIFACTSTAGINGDIRECTORY }}:${{ env.ARTDIR }} \
            rpcs3/rpcs3-ci-jammy:1.9 \
            /rpcs3/.ci/build-linux.sh

      - name: Upload artifacts
        uses: actions/upload-artifact@main
        with:
          name: RPCS3 for Linux (X64, clang)
          path: ${{ env.BUILD_ARTIFACTSTAGINGDIRECTORY }}/*.AppImage
          compression-level: 0

      - name: Get version info
        run: |
          COMM_TAG=$(awk '/version{.*}/ { printf("%d.%d.%d", $5, $6, $7) }' ./rpcs3/rpcs3_version.cpp)
          COMM_COUNT=$(git rev-list --count HEAD)
          COMM_HASH=$(git rev-parse --short=8 HEAD)
          echo "RPCS3_VERSION=${COMM_TAG}-${COMM_COUNT}-${COMM_HASH}" >> $GITHUB_ENV

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: latest
          name: "RPCS3 ${{ env.RPCS3_VERSION }}"
          files: ${{ env.BUILD_ARTIFACTSTAGINGDIRECTORY }}/*.AppImage
          prerelease: true
          fail_on_unmatched_files: false

      - name: Save build Ccache
        if: github.ref == 'refs/heads/master'
        uses: actions/cache/save@main
        with:
          path: ${{ env.CCACHE_DIR }}
          key: ${{ steps.restore-build-ccache.outputs.cache-primary-key }}

  Mac_Build:
    name: RPCS3 Mac Apple Silicon
    runs-on: macos-14
    env:
      CCACHE_DIR: /tmp/ccache_dir
      QT_VER: "6.10.2"
      QT_VER_MAIN: "6"
      LLVM_COMPILER_VER: "21"
      RELEASE_MESSAGE: ../GitHubReleaseMessage.txt
      AARCH64: 1
      RUN_UNIT_TESTS: github.event_name == 'pull_request' && 'ON' || 'OFF'
    steps:
      - name: Checkout repository
        uses: actions/checkout@main
        with:
          fetch-depth: 0

      - name: Restore Build Ccache
        uses: actions/cache/restore@main
        id: restore-build-ccache
        with:
          path: ${{ env.CCACHE_DIR }}
          key: ${{ runner.os }}-ccache-Apple Silicon-${{ github.run_id }}
          restore-keys: ${{ runner.os }}-ccache-Apple Silicon-

      - name: Restore Qt Cache
        uses: actions/cache/restore@main
        id: restore-qt-cache
        with:
          path: /tmp/Qt
          key: ${{ runner.os }}-qt-Apple Silicon-${{ env.QT_VER }}
          restore-keys: ${{ runner.os }}-qt-Apple Silicon-${{ env.QT_VER }}

      - name: Build
        run: .ci/build-mac.sh

      - name: Upload artifacts
        uses: actions/upload-artifact@main
        with:
          name: RPCS3 for Mac (Apple Silicon)
          path: ${{ env.BUILD_ARTIFACTSTAGINGDIRECTORY }}
          compression-level: 0

      - name: Get version info
        run: |
          COMM_TAG=$(awk '/version{.*}/ { printf("%d.%d.%d", $5, $6, $7) }' ./rpcs3/rpcs3_version.cpp)
          COMM_COUNT=$(git rev-list --count HEAD)
          COMM_HASH=$(git rev-parse --short=8 HEAD)
          echo "RPCS3_VERSION=${COMM_TAG}-${COMM_COUNT}-${COMM_HASH}" >> $GITHUB_ENV

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: latest
          name: "RPCS3 ${{ env.RPCS3_VERSION }}"
          files: ${{ env.BUILD_ARTIFACTSTAGINGDIRECTORY }}/*
          prerelease: true
          fail_on_unmatched_files: false

      - name: Save Build Ccache
        if: github.ref == 'refs/heads/master'
        uses: actions/cache/save@main
        with:
          path: ${{ env.CCACHE_DIR }}
          key: ${{ steps.restore-build-ccache.outputs.cache-primary-key }}

      - name: Save Qt Cache
        if: github.ref == 'refs/heads/master'
        uses: actions/cache/save@main
        with:
          path: /tmp/Qt
          key: ${{ steps.restore-qt-cache.outputs.cache-primary-key }}

  Windows_Build:
    name: RPCS3 Windows MSVC
    runs-on: windows-2025
    env:
      COMPILER: msvc
      QT_VER_MAIN: "6"
      QT_VER: "6.10.2"
      QT_VER_MSVC: "msvc2022"
      QT_DATE: "202601261212"
      LLVM_VER: "19.1.7"
      VULKAN_VER: "1.3.268.0"
      VULKAN_SDK_SHA: "8459ef49bd06b697115ddd3d97c9aec729e849cd775f5be70897718a9b3b9db5"
      CCACHE_SHA: "859141059ac950e1e8cd042c66f842f26b9e3a62a1669a69fe6ba180cb58bbdf"
      CCACHE_BIN_DIR: 'C:\ccache_bin'
      CCACHE_DIR: 'C:\ccache'
      CCACHE_INODECACHE: "true"
      CCACHE_SLOPPINESS: "time_macros"
      DEPS_CACHE_DIR: ./dependency_cache
    steps:
      - name: Checkout repository
        uses: actions/checkout@main
        with:
          fetch-depth: 0

      - name: Setup NuGet
        uses: nuget/setup-nuget@v2

      - name: Restore NuGet packages
        run: nuget restore rpcs3.sln

      - name: Setup env
        shell: pwsh
        run: |
          echo "QTDIR=C:\Qt\${{ env.QT_VER }}\${{ env.QT_VER_MSVC }}_64" >> ${{ github.env }}
          echo "VULKAN_SDK=C:\VulkanSDK\${{ env.VULKAN_VER }}" >> ${{ github.env }}

      - name: Get Cache Keys
        run: .ci/get_keys-windows.sh

      - name: Restore Build Ccache
        uses: actions/cache/restore@main
        id: restore-build-ccache
        with:
          path: ${{ env.CCACHE_DIR }}
          key: "${{ runner.os }}-ccache-${{ env.COMPILER }}-${{ github.run_id }}"
          restore-keys: ${{ runner.os }}-ccache-${{ env.COMPILER }}-

      - name: Restore Dependencies Cache
        uses: actions/cache/restore@main
        id: restore-dependencies-cache
        with:
          path: ${{ env.DEPS_CACHE_DIR }}
          key: "${{ runner.os }}-${{ env.COMPILER }}-${{ env.QT_VER }}-${{ env.VULKAN_SDK_SHA }}-${{ env.CCACHE_SHA }}-${{ hashFiles('llvm.lock') }}"
          restore-keys: ${{ runner.os }}-${{ env.COMPILER }}-

      - name: Download and unpack dependencies
        run: |
          .ci/setup-windows.sh
          .ci/setup-windows-ci-vars.sh win64 msvc

      - name: Export Variables
        run: |
          while IFS='=' read -r key val; do
            [[ -z "$key" || "$key" =~ ^# ]] && continue
            echo "$key=$val" >> "${{ github.env }}"
          done < .ci/ci-vars.env

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@main

      - name: Compile RPCS3
        shell: pwsh
        run: msbuild rpcs3.sln /p:Configuration=Release /v:minimal /p:Platform=x64 /p:PreferredToolArchitecture=x64 /p:CLToolPath=${{ env.CCACHE_BIN_DIR }} /p:UseMultiToolTask=true /p:CustomAfterMicrosoftCommonTargets="${{ github.workspace }}\buildfiles\msvc\ci_only.targets"

      - name: Run Unit Tests
        if: github.event_name == 'pull_request'
        shell: pwsh
        run: build\lib\Release-x64\rpcs3_test.exe

      - name: Pack up build artifacts
        run: |
          mkdir -p "${{ env.BUILD_ARTIFACTSTAGINGDIRECTORY }}"
          .ci/deploy-windows.sh

      - name: Upload artifacts (7z)
        uses: actions/upload-artifact@main
        with:
          name: RPCS3 for Windows (MSVC)
          path: ${{ env.BUILD_ARTIFACTSTAGINGDIRECTORY }}
          compression-level: 0
          if-no-files-found: error

      - name: Get version info
        run: |
          COMM_TAG=$(awk '/version{.*}/ { printf("%d.%d.%d", $5, $6, $7) }' ./rpcs3/rpcs3_version.cpp)
          COMM_COUNT=$(git rev-list --count HEAD)
          COMM_HASH=$(git rev-parse --short=8 HEAD)
          echo "RPCS3_VERSION=${COMM_TAG}-${COMM_COUNT}-${COMM_HASH}" >> $GITHUB_ENV

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: latest
          name: "RPCS3 ${{ env.RPCS3_VERSION }}"
          files: ${{ env.BUILD_ARTIFACTSTAGINGDIRECTORY }}/*
          prerelease: true
          fail_on_unmatched_files: false

      - name: Save Build Ccache
        if: github.ref == 'refs/heads/master'
        uses: actions/cache/save@main
        with:
          path: ${{ env.CCACHE_DIR }}
          key: ${{ steps.restore-build-ccache.outputs.cache-primary-key }}

      - name: Save Dependencies Cache
        if: github.ref == 'refs/heads/master'
        uses: actions/cache/save@main
        with:
          path: ${{ env.DEPS_CACHE_DIR }}
          key: ${{ steps.restore-dependencies-cache.outputs.cache-primary-key }}
